Add HealthCheck
husarion/orbbec-camera-docker pull request #1
Opened 2023-11-06 15:41 UTC by rafal-gorecki

2023-11-21 09:21 UTC, delihus approved these changes

2023-11-21 12:19 UTC, delihus requested changes

2023-11-21 12:19 UTC, delihus commented on Dockerfile
> +            ament_target_dependencies(healthcheck_node rclcpp std_msgs sensor_msgs)\n \
```suggestion
            ament_target_dependencies(healthcheck_node rclcpp sensor_msgs)\n \
```

2023-11-21 12:19 UTC, delihus commented on Dockerfile
> +    sed -i '/find_package(std_msgs REQUIRED)/a \
std_msgs is not necessary

2023-11-21 12:28 UTC, delihus requested changes

2023-11-21 12:28 UTC, delihus commented on Dockerfile
> +    ros2 pkg create healthcheck_pkg --build-type ament_cmake --dependencies rclcpp std_msgs && \
```suggestion
    ros2 pkg create healthcheck_pkg --build-type ament_cmake --dependencies rclcpp sensor_msgs && \
```

2023-11-21 13:47 UTC, delihus requested changes

2023-11-21 13:47 UTC, delihus commented on Dockerfile
> +    sed -i '/find_package(sensor_msgs REQUIRED)/a \
there should be `find_package(rclcpp REQUIRED)` i think

2023-11-27 07:59 UTC, delihus approved these changes

2023-11-27 08:47 UTC, rafal-gorecki commented on Dockerfile
>      colcon build --event-handlers  console_direct+  --cmake-args  -DCMAKE_BUILD_TYPE=Release
```suggestion
    colcon build --cmake-args  -DCMAKE_BUILD_TYPE=Release
```

2023-11-27 08:48 UTC, merged